server:
  port: 8083

spring:
  application:
    name: RATINGS-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true